### ISSUE TITLE
Remove Linq.

### ISSUE THREAD

**Issue by Martenfur** [loodakrawa/SpriterDotNet#117]
You have a couple of places there you use System.Linq -- particularly, in Animator class. Linq is very slow and generates garbage. You're making a library for games, where performance matters. It won't be hard to replace Linq,

**Comment by loodakrawa** [comment]
Did you even check HOW Linq is being used?

**Comment by Martenfur** [comment]
Yes. You're converting an array to a dictionary, which can be done with a for loop, and trying to get first element of that dictionary (???) while having access to that original array (**???**).

Instead of overengineering you can do this:

```
// Instead of
Animations = entity.Animations.ToDictionary(a => a.Name, a => a);

// Do:
Animations = new Dictionary(string, SpriterAnimation);
for (var i = 0; i < entity.Animations.Length; i += 1)
{
  Animations.Add(entity.Animations[i].Name, entity.Animations);
}
_defaultAnimationName = entity.Animations[0].Name;
```

```
// Instead of
Play(Animations.Keys.First();

// Do:
Play(_defaultAnimationName);
```

**Comment by loodakrawa** [comment]
What I meant is how it's being used in terms of impact. More precisely, in the Animator class it is used:

- In the constructor, which is invoked only once by definition
- In the update function it is called once, and only in the edge case where the animation is not explicitly set which is very unlikely in a real world scenario

Based on this, talking about it not being performant in this case makes little sense especially since it would make it less readable. However, if you do think this is causing a bottleneck, feel free to prove it with actual code and numbers and not just a generalised statement about it. This is computer science after all, not computer opinions.

That being said, in the version 2.0 most likely there won't be any Linq.
