### ISSUE TITLE
Simplify public interface.

### ISSUE THREAD

**Issue by Martenfur** [loodakrawa/SpriterDotNet#118]
This is what you need to do to set up a single animation.

```CSharp
public static readonly Config Config = new Config
{
	MetadataEnabled = true,
	EventsEnabled = true,
	PoolingEnabled = true,
	TagsEnabled = true,
	VarsEnabled = true,
	SoundsEnabled = false
};
DefaultProviderFactory<ISprite, SoundEffect> factory = new DefaultProviderFactory<ISprite, SoundEffect>(Constants.Config, true);

Stack<SpriteDrawInfo> drawInfoPool = new Stack<SpriteDrawInfo>();

SpriterContentLoader loader = new SpriterContentLoader(Content, scmlPath);
loader.Fill(factory);
foreach (var entity in loader.Spriter.Entities)
{
	var animator = new MonoGameAnimator(entity, factory, drawInfoPool);
	animators.Add(animator);
}
```

This is horribly overcomplicated. Ideally, it should look roughly like this:

```CSharp
var template = new SpriterAnimatorTemplate(Content, scmlPath);
var animator = template.MakeAnimator();
```

Additional configs could be moved away to a separate controller class.

**Comment by loodakrawa** [comment]
Not really. You can do something as simple as:

```CSharp
var factory = new DefaultProviderFactory<ISprite, SoundEffect>(new Config());
var loader = new SpriterContentLoader(Content, scmlPath);
loader.Fill(factory);
var animator = new MonoGameAnimator(loader.Spriter.Entities.First(), factory);
```

**Comment by Martenfur** [comment]
My version is twice as simple, tho. : - ) 

Also this way you'll create a separate pool for every single animation, which is a waste. n fact, I don't understand why you even need to expose the pool and pass it separately. You can just make is a private static field.

**Comment by loodakrawa** [comment]
I agree, it is twice as simple.

I exposed the pool because:
- I like giving the user as much control as possible
- Using the pool for other parts of the game
- Multithreading support - in case things are animated in different threads. This COULD be done as some kind of per-thread static pool, but still, I prefer to leave it to the user

As I mention for other things as well, version 2 SHOULD handle all of this better, without really the need for pooling in the first place.
