### ISSUE TITLE
No overload for method SpriterImporter 

### ISSUE THREAD

**Issue by aolba** [loodakrawa/SpriterDotNet#15]
using the unity plug with unity 5.0.0f4 I get this error: "Assets/SpriterDotNet/SpriterImporter.cs(108,49): error CS1501: No overload for method `LoadAssetAtPath' takes `1' arguments" when drop the unitypackage...

**Comment by aolba** [comment]
I manage to remove the error... it seems it is related to some update in unity/LoadAssetAtPath...

GameObject existing = AssetDatabase.LoadAssetAtPath(prefabPath, typeof( GameObject ) ) as GameObject;
and
asset = AssetDatabase.LoadAssetAtPath (path, typeof(T) ) as T;

But still can't see anything in the scenes with the examples.

**Comment by loodakrawa** [comment]
I wasn't aware of that, but as you already discovered, Unity changed the API in one of the updates before I started with this library. The example scenes don't work because they failed during import due to that error. If you re-import the scml files after your change, you should be able to get them working (possibly having to replace the objects in scene).
