### ISSUE TITLE
Question regarding SpriterObjectType

### ISSUE THREAD

**Issue by wighawag** [loodakrawa/SpriterDotNet#36]
in the function addSpatialData (https://github.com/loodakrawa/SpriterDotNet/blob/master/SpriterDotNet/SpriterProcessor.cs#L283)
there is a switch statement that go over some of the SpriterObjectType.

I guess it is not possible that it will be of the type whose the "case" is missing (Bone,Sound,Variable )?

Why do these SpriterObjectType exist then (they are not checked anywhere)?

for Sound is it because it can never be on a timeline and always is on a SoundLine?
What about Bone and Variable ?

Thanks

**Comment by loodakrawa** [comment]
This method takes care of spatial data only. There are separate methods for sounds, variables, etc. Bones are not included because they're not needed since all sprites/boxes/points already have all transforms calculated by this point.

Could you please ask questions on the forum thread instead of opening them as issues here? I'm trying to keep this for actual issues/bugs. Thanks.
