### ISSUE TITLE
note about imported as Sprites

### ISSUE THREAD

**Issue by aolba** [loodakrawa/SpriterDotNet#47]
I see there is note about the images in the spriter project:
**IMPORTANT: Make sure that all the images referenced in the .scml are imported as Sprites.**
But I don't remember this was necessary on my previous test with SpriterDotNet.Unity
I see in the demo package this is fine, all the images are aprites, but even when I make this change to every image it doesn’t work on my current test. I have to make it BEFORE I import the spriter project.
Do you use any script to convert the images to sprites on the import step on the fly? I doesn’t seem to work now. I think I see this set on the previous version I test, but I'm not sure.
This will be a new part of the work flow ?

**Comment by loodakrawa** [comment]
It was always necessary since the importer tries to load Sprites. I just added the notice later.

If you change the images to the Sprite type you should reimport all .scmls that reference those sprites.

Changing the type of referenced images while loading the .scml is a good idea - I'll investigate if that's possible in Unity. If you know how can it be done feel free to submit a PR.
