### ISSUE TITLE
AnimationFinished Event Not Correct

### ISSUE THREAD

**Issue by ademartini** [loodakrawa/SpriterDotNet#74]
If you do a blended transition from animation A to animation B, the first animation complete event for B doesn't happen at the completion of B.  It also seems to vary in time in an unpredictable way.  Any idea?

**Comment by loodakrawa** [comment]
Do the animations have the same length? If not, that's probably what causes the difference in timing since the animations are blended in a normalised way. E.g. if animation A is 1000ms long and animation B is 2000ms long and the current time in animation A is at 250ms (0.25) that means it's going to get blended with animation B at 0.25 or 500ms.

As for the event firing - it should fire when the remainder of animation B finishes. If this doesn't happen - what are the lengths of your animations A and B?

**Comment by ademartini** [comment]
Hey @loodakrawa thanks for the response.  So I have two animations: animation A is 600 ms and animation B is 1000ms.  Sometime during animation A, I call transition to change to change to animation B.  When I do this, for some reason the event for animation B doesn't happen correctly.  I would expect that the event for B should always happen when B completes.

**Comment by loodakrawa** [comment]
I'm not able to replicate the issue. Can you send me your animation (or a modified version that exhibits the same behaviour) so I can take a look? My email: loodakrawa at gmail
