### ISSUE TITLE
Doesn't work with Unity 2017.1

### ISSUE THREAD

**Issue by ghost** [loodakrawa/SpriterDotNet#86]
like the title says.

**Comment by loodakrawa** [comment]
It was bound to happen. I put the development of the Unity version on hold at least until they decide to support a more modern .NET version. I think this means waiting for .NET Standard 2.0 since they said they will support it once it comes out. Unity 2017.1.0 seems to be on the right track with the (experimental) support for C# 6 and .NET 4.6.

**Comment by therobear** [comment]
What doesn't work? What errors are you getting? I started using it with Unity 2017.1 with no issues.

**Comment by paulevans** [comment]
FWIW there was some namespace collisions. I fiddled about with it locally and stuck the spriterdotnet plugin things in a spriterdotnet namespace and it worked fine.

**Comment by loodakrawa** [comment]
What was the collision? It's a bit strange since the SdN classes are already in the SpriterDotNet and SpriterDotNetUnity namespaces. I recently upgraded my Unity to 2017.2 and there were no issues, at least in an empty project.

**Comment by paulevans** [comment]
I think it was that there was a collision because of the usings - and it was something like Sprite colliding with Unity's.
I should have said something at the time - sorry I wasn't more precise.  I subscribed to this bug many weeks ago now, tinkered and cannot recall what Happened clearly :/

**Comment by loodakrawa** [comment]
Ah ok, I get it. I feared this was one of many Unity's quirks. Thankfully we have namespaces for that. I'll leave this closed because there seem to be no real issues.
